# Generated by Django 2.2 on 2022-12-23 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_contracts', '0001_initial'),
        ('hr_leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayroolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.FloatField(default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_leave.LeaveModel'), verbose_name='fine')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('salary', models.FloatField(default=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_contracts.ContractModel'), verbose_name='salary')),
                ('bonus', models.FloatField(default=0.0, verbose_name='bonus')),
                ('total', models.FloatField(default=0.0, verbose_name='total')),
                ('Contract_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_contracts.ContractModel')),
                ('leave_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_leave.LeaveModel')),
            ],
        ),
    ]
