# Generated by Django 2.0 on 2022-10-05 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_jobs', '0001_initial'),
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End Date')),
                ('salary', models.FloatField(default=0.0, verbose_name='Salary')),
                ('employee_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel')),
                ('job_id', models.ManyToManyField(to='hr_jobs.JobModel')),
            ],
        ),
    ]
