# Generated by Django 2.2 on 2022-11-24 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(max_length=20, verbose_name='Leave')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End Date')),
                ('fine', models.FloatField(default=0.0, verbose_name='Fine')),
                ('employee_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_employees.EmployeeModel')),
            ],
        ),
    ]
