# Generated by Django 2.0 on 2022-10-05 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='Birthday')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='imgs/')),
            ],
        ),
    ]
